config/routes.rb
Rails.application.routes.draw do
	get '/position', to: 'chessboard#position'
	get '/drill', to: 'chessboard#drill', as: 'drill'
  get '/edit', to: 'chessboard#edit', as: 'edit'

  root to: 'chessboard#drill'

  get 'users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  post '/moves', to: 'moves#create'
  get '/moves', to: 'moves#next_due_move'
  get '/moves/new', to: 'moves#new', as: 'new_move'
  post '/moves/:id/correct', to: 'moves#correct'
  post '/moves/:id/incorrect', to: 'moves#incorrect'
  get '/moves/position', to: 'moves#move_at_position'
  post '/moves/delete', to: 'moves#destroy'

  get '/positions', to: 'positions#index', as: 'positions'

  post '/positions', to: 'positions#create', as: 'create_position'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :user
  belongs_to :parent_position, class_name: 'Position', foreign_key: 'position_id'
  has_many :positions_moves, :dependent => :destroy
  has_many :resulting_positions, through: :positions_moves, source: :position 
  validates :position, uniqueness: { scope: :user_id }
  before_destroy :reset_parent

  def update_likelihood ratio
  	self.resulting_positions.each do |p|
  		p.update_likelihood ratio
  	end
  	self.likelihood *= ratio
  	self.save
  end

  private
  def reset_parent
  	if self.parent_position.moves.length <= 1
  		self.parent_position.learned = false
  		self.parent_position.save
  	end
  end 
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :user
  has_many :moves, foreign_key: 'position_id', dependent: :destroy
  has_many :positions_moves, dependent: :destroy
  has_many :parent_moves, through: :positions_moves, source: :move
  validates :fen, uniqueness: { scope: :user_id }

  def update_likelihood ratio
  	self.moves.each do |m|
  		m.update_likelihood ratio
  	end
  	self.likelihood *= ratio
  	self.save
  end
end

app/models/positions_move.rb
class PositionsMove < ApplicationRecord
  belongs_to :move
  belongs_to :position

  before_destroy :destroy_positions

  private
  def destroy_positions
		if self.position.parent_moves.length <= 1
			self.position.destroy
		end
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates_uniqueness_of :email

	has_many :moves
	has_many :positions

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user ? @user.authenticate(params[:password]) : false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/chessboard_controller.rb
class ChessboardController < ApplicationController

	def drill
		if !current_user
			redirect_to '/login'
		end
	end

	def edit
		if !current_user
			redirect_to '/login'
		end
	end

	def position
		@position = 'rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1'
		render :json => {position: @position}
	end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
	include ActionView::Helpers::DateHelper
	def next_due_move
		@move = current_user.moves.min_by {|m| m.due}
		if !@move or @move.due > DateTime.now
			render :json => {move: "no move"}
		else
			render :json => @move
		end
	end

	def new

	end

	def move_at_position
		@move = Move.find_by(user: current_user, position: params[:fen])
		render :json => @move
	end

	def index
		@moves = current_user.moves
	end

	def create
		@move = Move.new move_params
		@move.user = current_user
		@move.due = DateTime.now + 30.seconds
		@move.streak = 0
		@move.parent_position = Position.find(@move.position_id)
		if @move.save
			Position.where({user: current_user, fen: @move.position}).update_all(learned: true)
			render :json => @move
		else
			flash[:error] = "error saving move"
		end
	end

	def destroy
		@move = Move.find_by(user: current_user, position: params[:fen])
		@move.destroy
	end

	def correct
		@move = Move.find(params[:id])
		@move.streak += 1
		@move.due = DateTime.now + 30.seconds * 5**@move.streak
		@move.save
		render :json => {time: distance_of_time_in_words(DateTime.now, @move.due)}
	end

	def incorrect
		@move = Move.find(params[:id])
		@move.streak = 0
		@move.due = DateTime.now + 30.seconds
		@move.save
	end

	private

	def move_params
		params.require(:move).permit(:position, :resulting_position, :san, :likelihood, :due, :streak, :position_id)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def index
		@position = current_user.positions.where(learned: false).max_by {|p| p.likelihood}
		render :json => @position
	end

	def new
	end

	def create
		@position = Position.new position_params
		@existing = Position.find_by(fen: @position.fen, user_id: current_user.id)
		@move = Move.find_by(position: @position.fen, user_id: current_user.id)
		if @existing
			@existing.update(likelihood: @existing.likelihood + @position.likelihood)
			@existing.parent_moves << Move.find(params[:parent_id])
		elsif @move
			@move.update_likelihood((@move.likelihood+@position.likelihood)/@move.likelihood)
		else
			@position.user = current_user
			@position.learned = false
			if (params[:parent_id])
				@position.parent_moves << Move.find(params[:parent_id])
			end
			@position.save
		end
	end

	private

	def position_params
		params.require(:position).permit(:fen, :likelihood, :parent_moves)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		user_params = params.require(:user).permit(:email, :password)
		@user = User.confirm(user_params)
		if @user
			login(@user)
			
			redirect_to root_path
		else
			flash[:error] = "Wrong username/password"
			redirect_to login_path
		end
	end

	def destroy
		logout
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			login(@user)
			redirect_to root_path
		else
			flash[:error] = @user.errors.full_messages.join(" ")
			render new_user_path
		end
	end

	def user_params
		params.require(:user).permit(:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
  	@current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chessboard/drill.html.erb
<% content_for :js do %>
	<script>
		$(document).ready(function(){
			var fenStr = "";
			drillNextMove();
		});
		function renderBoard(data) {
			if (data.move == "no move"){
				$.ajax({
					url: '/positions',
					dataType: 'json'
				}).then(renderNewBoard);
			}

			$('#message').html("Play the right move!");
			fenStr = data.position;
			var board,
			game = new Chess(fenStr),
			movesEl = $('#moves');
			movesEl.empty();
			var onDragStart = function(source, piece, position, orientation) {
				if (game.game_over() === true ||
					(game.turn() === 'w' && piece.search(/^b/) !== -1) ||
					(game.turn() === 'b' && piece.search(/^w/) !== -1)) {
					return false;
				}
			};

			var onDrop = function(source, target) {
			  var prev = game.fen();
			  var move = game.move({
			  	from: source,
			  	to: target,
			    promotion: 'q'
			  });
			  if (move === null)
			  	return 'snapback';
			  else {
			  	if (move.san == data.san) {
			  		$.ajax({
			  			url: '/moves/'+data.id+'/correct',
			  			type: 'POST'
			  		}).then(function(time) {
			  			$('#correct').html("Correct! Next due in "+time.time);
			  			$('#right').effect("highlight", {}, 1000);
			  			drillNextMove();
			  		});
			  	}
			  	else {
			  		$.ajax({
			  			url: '/moves/'+data.id+'/incorrect',
			  			type: 'POST'
			  		}).then(function() {
			  			$('#correct').html("Incorrect! Correct was " + data.san + ". Next due in 30 seconds.");
			  			$('#right').effect("highlight", {color: '#ff9999'}, 1000);
			  			drillNextMove();
			  		});
			  	}
			  }
			};

			var onSnapEnd = function() {
				board.position(game.fen());
			};

			if (game.turn() == 'b')
				var orientation = 'black';
			else
				var orientation = 'white';

			var cfg = {
				orientation: orientation,
				draggable: true,
				position: fenStr,
				onDragStart: onDragStart,
				onDrop: onDrop,
				onSnapEnd: onSnapEnd
			};
			board = ChessBoard('board', cfg);
		}

		function renderNewBoard(data) {
			$('#message').html("Add a new move!");
			if (!data) {
				var game = new Chess();
				$.ajax({
					url: '/positions',
					type: 'POST',
					data: {
						position: {
							fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
							likelihood: 1
						}
					}
				})
				$.ajax({
					url: 'https://explorer.lichess.ovh/master?fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
					dataType: 'json'
				}).then(function(lichessData){
					var total = lichessData.white+lichessData.draws+lichessData.black;
					var requests = 0;
					lichessData.moves.forEach((m) => {
						game.move(m.san);
						var pos = game.fen();
						var mTotal = m.white+m.draws+m.black;
						$.ajax({
							url: '/positions',
							type: 'POST',
							data: {
								position: {
									fen: pos,
									likelihood: mTotal/total
								}
							}
						}).then(() => {
							requests++;
							if (requests >= lichessData.moves.length)
								drillNextMove();
						});
						game.undo();
					});
				});
			}
			else {
				var fenStr = data.fen;
				var board,
				game = new Chess(fenStr),
				movesEl = $('#moves');

				var onDragStart = function(source, piece, position, orientation) {
					if (game.game_over() === true ||
						(game.turn() === 'w' && piece.search(/^b/) !== -1) ||
						(game.turn() === 'b' && piece.search(/^w/) !== -1)) {
						return false;
					}
				};

				var onDrop = function(source, target) {
				  var prev = game.fen();
				  var move = game.move({
				  	from: source,
				  	to: target,
				    promotion: 'q'
				  });

				  if (move === null)
				  	return 'snapback';
				  else if (!commonMoves.includes(move.san)) {
				  	game.undo();
				  	return 'snapback';
				  }
				  else makeMove(move, prev);
				};

				$('#right').off('click').on('click', '.move', function(event) {
					event.preventDefault();
					game.undo();
					var prev = game.fen();
					var from = event.target.id.slice(0,2);
					var to = event.target.id.slice(2,4);
					$('.square-'+from).removeClass("highlight");
					$('.square-'+to).removeClass("highlight");
					var move = game.move(event.target.id.slice(5));
					makeMove(move, prev);
				});

				
				$('#right').on('mouseenter', '.move', function(event) {
					var from = event.target.id.slice(0,2);
					var to = event.target.id.slice(2,4);
					$('.square-'+from).addClass("highlight");
					$('.square-'+to).addClass("highlight");
					board.position(game.fen());
					
				});
				$('#right').on('mouseleave', '.move', function(event) {
					var from = event.target.id.slice(0,2);
					var to = event.target.id.slice(2,4);
					$('.square-'+from).removeClass("highlight");
					$('.square-'+to).removeClass("highlight");
					board.position(game.fen());
				});


				var makeMove = function(move, prev) {
				  	$.ajax({
				  		url: 'https://explorer.lichess.ovh/master?fen='+game.fen(),
				  		dataType: "json"
				  	}).then(function(lichessData){
				  		var total = lichessData.white+lichessData.draws+lichessData.black;
				  		var requests = 0;
				  		$.ajax({
				  			url: '/moves',
				  			type: 'POST',
				  			data: {
				  				move: {
				  					position_id: data.id,
				  					position: prev,
				  					resulting_position: game.fen(),
				  					san: move.san,
				  					likelihood: data.likelihood
				  				}
				  			}
				  		}).then((moveData) => {
				  			requests++;
				  			if (requests >= lichessData.moves.length + 1)
				  				drillNextMove();
				  			lichessData.moves.forEach((m) => {
				  				game.move(m.san);
				  				var pos = game.fen();
				  				var mTotal = m.white+m.draws+m.black;
				  				$.ajax({
				  					url: '/positions',
				  					type: 'POST',
				  					data: {
				  						position: {
				  							fen: pos,
				  							likelihood: (mTotal/total * data.likelihood) * (1- Math.pow(.5, mTotal))
				  						},
				  						parent_id: moveData.id
				  					}
				  				}).then(() => {
				  					requests++;
				  					if (requests >= lichessData.moves.length + 1) {
				  						$('#correct').empty();
				  						drillNextMove();
				  					}
				  				});
				  				game.undo();
				  			});
				  		});
				  	});
				  }

				var onSnapEnd = function() {
					board.position(game.fen());
				};

				if (game.turn() == 'b')
					var orientation = 'black';
				else
					var orientation = 'white';
				var cfg = {
					orientation: orientation,
					draggable: true,
					position: fenStr,
					onDragStart: onDragStart,
					onDrop: onDrop,
					onSnapEnd: onSnapEnd
				};
				board = ChessBoard('board', cfg);
				var commonMoves = [];
				$.ajax({
				  	url: 'https://explorer.lichess.ovh/master?fen='+game.fen(),
				  	dataType: "json"
				  }).then(function(lichessData){
				  	movesEl.empty();
				  	var total = lichessData.white+lichessData.draws+lichessData.black;
				  	lichessData.moves.forEach((move) => {
				  		var moveTotal = move.white+move.draws+move.black;
				  		var percent = moveTotal/total * 100;
				  		if (percent > 0.1){
				  			movesEl.append("<p><button class='move' id='"+move.uci+"-"+move.san+"'>"+move.san+": "+percent.toFixed(1)+"%</button></p>");
				  			commonMoves.push(move.san);
				  		}
				  	});
				  });
			}
		}  

		function drillNextMove(){
			$.ajax({
				url: "/moves",
				dataType: "json"
			}).then(renderBoard);
		}

	</script>
<% end %>
<div id="board" style="width: 600px"></div>
<div id="right">
	<div id="correct"></div>
	<div id="message"></div>
	<div id="moves"></div>
</div>
<div id="bottom">
	<%= link_to "Edit Moves", edit_path %>
</div>

app/views/chessboard/edit.html.erb
<% content_for :js do %>
  <script>
    $(document).ready(function(){
    	renderBoard();
		});   

		function renderBoard() {
			var board,
			game = new Chess(),
		  movesEl = $('#moves');

		  $('#back').click(function() {
		  	game.undo();
		  	board.position(game.fen());
		  	updateStatus();
		  });

			var onDragStart = function(source, piece, position, orientation) {
			  if (game.game_over() === true ||
			      (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
			      (game.turn() === 'b' && piece.search(/^w/) !== -1)) {
			    return false;
			  }
			};

			var onDrop = function(source, target) {
			  var move = game.move({
			    from: source,
			    to: target,
			    promotion: 'q'
			  });
			  if (move === null)
			  	return 'snapback';
			  updateStatus();
			};

			var onSnapEnd = function() {
			  board.position(game.fen());
			};

			var updateStatus = function() {
			  $.ajax({
			  	url: '/moves/position',
			  	dataType: 'json',
			  	data: {
			  		fen: game.fen()
			  	}
			  }).then(function(moveData){
			  	board.position(game.fen());
			  	$.ajax({
			  	url: 'https://explorer.lichess.ovh/master?fen='+game.fen(),
			  	dataType: "json"
				  }).then(function(lichessData){
				  	movesEl.empty();
				  	var total = lichessData.white+lichessData.draws+lichessData.black;
				  	lichessData.moves.forEach((move) => {
				  		var moveTotal = move.white+move.draws+move.black;
				  		var percent = moveTotal/total * 100;
				  		if (percent > 0.1) {
				  			if (moveData && move.san == moveData.san)
				  				movesEl.append("<p><button class='move' id='"+move.uci+"-"+move.san+"'><b>"+move.san+": "+percent.toFixed(1)+"%</b></button><button class='delete'>Delete</button></p>");
				  			else
				  				movesEl.append("<p><button class='move' id='"+move.uci+"-"+move.san+"'>"+move.san+": "+percent.toFixed(1)+"%</button></p>");
				  		}
				  	});
				  	$('button.delete').click(function(){
				  		if (confirm("Are you sure you want to delete this move? (All progress will be lost)")){
				   			$.ajax({
				   				url: '/moves/delete',
				   				type: 'POST',
				   				data: {
				   					fen: game.fen()
				   				}
				   			}).then(updateStatus);
				   		}
			   		});
				  });
			  });
			};

			$('#right').off('click').on('click', '.move', function(event) {
					event.preventDefault();
					var from = event.target.id.slice(0,2);
					var to = event.target.id.slice(2,4);
					$('.square-'+from).removeClass("highlight");
					$('.square-'+to).removeClass("highlight");
					game.move(event.target.id.slice(5));
					updateStatus();
				});
			$('#right').on('mouseenter', '.move', function(event) {
					var from = event.target.id.slice(0,2);
					var to = event.target.id.slice(2,4);
					$('.square-'+from).addClass("highlight");
					$('.square-'+to).addClass("highlight");
					board.position(game.fen());
					
				});
				$('#right').on('mouseleave', '.move', function(event) {
					var from = event.target.id.slice(0,2);
					var to = event.target.id.slice(2,4);
					$('.square-'+from).removeClass("highlight");
					$('.square-'+to).removeClass("highlight");
					board.position(game.fen());
				});

			if (game.turn() == 'b')
				var orientation = 'black';
			else
				var orientation = 'white';
			var cfg = {
				orientation: orientation,
			  draggable: true,
			  position: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
			  onDragStart: onDragStart,
			  onDrop: onDrop,
			  onSnapEnd: onSnapEnd
			};
			board = ChessBoard('board', cfg);
			updateStatus();
		}  
  </script>
<% end %>

<div id="board" style="width: 600px"></div>
<div id="right">
	<div id ="back-button">
		<button id="back">Back</button>
	</div>
	<div id="correct"></div>
	<div id="message"></div>
	<div id="moves"></div>
</div>
<div id="bottom"><%= link_to "Back to Drill", drill_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChessPrep</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>

   <link href="<%= image_path("chesspieces/wikipedia/wP.png") %>" rel="shortcut icon" />
    <%= yield :js %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <h1>ChessPrep</h1>
        <div id="login">
          <% if current_user %>
            <%= link_to "Logout", '/logout' %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/moves/new.html.erb
<% content_for :js do %>
  <script>
    $(document).ready(function(){
    	console.log("page loaded");
    	$.ajax({
    		url: '/positions',
    		dataType: 'json'
    	}).then(renderBoard);
	

});
   function renderBoard(data) {
		console.log(data);
		var fenStr = data.fen;

	var board,
	  game = new Chess(fenStr),

	  statusEl = $('#status'),
	  fenEl = $('#fen'),
	  pgnEl = $('#pgn'),
	  movesEl = $('#moves');

	// do not pick up pieces if the game is over
	// only pick up pieces for the side to move
	var onDragStart = function(source, piece, position, orientation) {
	  if (game.game_over() === true ||
	      (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
	      (game.turn() === 'b' && piece.search(/^w/) !== -1)) {
	    return false;
	  }
	};

	var onDrop = function(source, target) {
	  // see if the move is legal
	  let prev = game.fen();
	  var move = game.move({
	    from: source,
	    to: target,
	    promotion: 'q' // NOTE: always promote to a queen for example simplicity
	  });


	  // illegal move
	  if (move === null)
	  	return 'snapback';
	  else {
	  	$.ajax({
	  	url: 'https://expl.lichess.org/master?fen='+game.fen(),
	  	dataType: "json"
	  }).then(function(lichessData){
	  	let total = lichessData.white+lichessData.draws+lichessData.black;
	  	lichessData.moves.forEach((m) => {
	  		game.move(m.san);
	  		let pos = game.fen();
	  		let mTotal = m.white+m.draws+m.black;
	  		$.ajax({
	  			url: '/positions',
	  			type: 'POST',
	  			data: {
	  				position: {
		  				fen: pos,
		  				likelihood: mTotal/total * data.likelihood
		  			}
	  			}
	  		})
	  		game.undo();
	  	});
	  	$.ajax({
		  	url: '/moves',
		  	type: 'POST',
		  	data: {
		  		move: {
		  		position: prev,
		  		resulting_position: game.fen(),
		  		san: move.san,
		  		likelihood: data.likelihood
			  	}
			  }
		  }).then(function(move) {
		  });
	  });

	  }

	  // updateStatus();
	};

	// update the board position after the piece snap 
	// for castling, en passant, pawn promotion
	var onSnapEnd = function() {
	  board.position(game.fen());
	};

	var updateStatus = function() {
	  var status = '';

	  var moveColor = 'White';
	  if (game.turn() === 'b') {
	    moveColor = 'Black';
	  }

	  // checkmate?
	  if (game.in_checkmate() === true) {
	    status = 'Game over, ' + moveColor + ' is in checkmate.';
	  }

	  // draw?
	  else if (game.in_draw() === true) {
	    status = 'Game over, drawn position';
	  }

	  // game still on
	  else {
	    status = moveColor + ' to move';

	    // check?
	    if (game.in_check() === true) {
	      status += ', ' + moveColor + ' is in check';
	    }
	  }

	  $.ajax({
	  	url: 'https://expl.lichess.org/master?fen='+game.fen(),
	  	dataType: "json"
	  }).then(function(lichessData){
	  	movesEl.empty();
	  	let total = lichessData.white+lichessData.draws+lichessData.black;
	  	lichessData.moves.forEach((move) => {
	  		let moveTotal = move.white+move.draws+move.black;
	  		let percent = moveTotal/total * 100;
	  		if (percent > 0.1)
	  			movesEl.append("<p>"+move.san+": "+percent.toFixed(1)+"%</p>");
	  	});
	  });



	  statusEl.html(status);
	  fenEl.html(game.fen());
	  pgnEl.html(game.pgn());
	};

	var cfg = {
	  draggable: true,
	  position: fenStr,
	  onDragStart: onDragStart,
	  onDrop: onDrop,
	  onSnapEnd: onSnapEnd
	};
	board = ChessBoard('board', cfg);

	updateStatus();
} 

  </script>
<% end %>
Add a move!
<div id="board" style="width: 600px"></div>
<p>Status: <span id="status"></span></p>
<p>Fen: <span id="fen"></span></p>
<div id="moves"></div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.email_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

<%= flash[:error] %>

<p>Already have an account? <%= link_to "Log in", "/login" %></p>

<div id="welcome">
	<p>
		Welcome to ChessPrep! ChessPrep is a site that allows chess players to build and practice their opening repertoire.
		</p><p>After you create an account, ChessPrep will show you positions and ask you to enter your move of choice for those positions. To help you decide, a list of the most popular moves from that position will be shown based on a database of over a million master level games. <p>After you choose your moves, you will be drilled on those moves using a method called spaced repetition. The more times you play the right move, the less often you will be asked to repeat that move.</p><p> As you practice your moves, ChessPrep will calculate the most likely positions you are to face based on your previously entered moves. When you no longer have moves to practice, ChessPrep will show you the next most likely position and ask you for a new move. This lets you prioritize and focus on only the most relevant positions and enables you to have a well balanced opening repertoire.
	</p>
</div>